[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["nodejs", "npm"]
cmds = ["npm config set fetch-retry-maxtimeout 600000"]

[phases.build]
cmds = ["npm ci --production=false"]

[phases.install]
cmds = ["npm run build"]

[phases.cleanup]
cmds = ["npm prune --production"] 